<?php include 'include/header.php' ?>
<h2>The Origin of Lion Dance</h2>
<p>
Lion Dancing is an important tradition in Asia, especially China. Usually the lion dance is performed during festive occasions like Chinese New Year, Grand opening of business' and weddings. It is believed that loud noises scare away evil spirits so firecrackers and loud banging of the music are often used to scare away evil or bad karma. The lion Dance brings good luck and happiness.
</p>
<p>
There are many stories about the origins of lion dance; here is one of the most popular stories about origin of lion dance. Legend has it that the Emperor had a dream one night in which he became separated from his army and lost; with no food or drink he began to panic. He then saw a strange looking animal that protected him and guided him back to the palace. The next morning, the Emperor described the dream to his ministers. One minister told the Emperor that the strange animal resembled a creature from the West, the Lion.
</p>
<h2>Style of Lion</h2>
<p>The Chinese Southern dance is more symbolic. It is usually performed as a ceremony to scare away evil spirits and to summon luck and fortune. The Chinese southern lion exhibits a wide variety of colour and has a distinctive head with large eyes (of an eagle), a mirror on the forehead (demons are supposedly scared of their own reflection), and a single horn at center of the head. Lion dance costumes are considered to be spiritually protective when used as they are traditionally blessed before usage. Lion dances can be broadly categorized into three styles, Chinese Northern , Chinese Southern , and Taiwanese . There are two styles of Southern lion dance, one style is from Fujian and the other is from Guangdong (Canton). which is also the most popular. The Cantonese lion can be divided into two styles one is Foshan, which is very popular in Hong Kong and most Chinese communities around the World. The other is the Heshan, which is popular in Malaysia, Singapore and with competition teams.</p>
<p>During the Chinese New Year, lion dance troupes from the Chinese martial art schools or Chinese guild and associations will visit the houses and shops of the Chinese community to perform the traditional custom of "cai ching" , literally means "plucking the greens", a quest by the 'lion' to pluck the auspicious green normally 'vegetables' like lettuce which in Chinese called 'cai' that sound like 'cai'(fortune) and auspicious fruit like oranges tied to a "Red Envelope" containing money; either hang highly or just put on a table in front of the premises. The "lion" will dance and approach the "green" and "red evelope" like a curious cat, to "eat the green" and "spit" it out leave it in a nice arrangement, like an auspicious character but keep the "red envelope". The lion dance is believed to bring good luck and fortune to the business and the troupe is rewarded with the "red envelope". Different types of vegetables, fruits, foods or utensils with auspicious and good symbolic meanings; for instance pineapples, pamelos, bananas, oranges, sugar cane shoots, coconuts, beer, clay pots or even crabs can be used to be the "greens" to be "plucked" to give different difficulty and challenge for the lion dance performers. But the difficulties of the challenge should comes with the bigger the rewards of the "red envelope" given.</p>
<?php include 'include/footer.php' ?>